# -*- coding: utf-8 -*-
"""derinogrenme_odev_plantvillage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJoJKyPytvKsIe2DQ-IYkseezblqTlF4
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, WeightedRandomSampler, Subset, Dataset, random_split
from torchvision import models
import numpy as np
from pathlib import Path
import zipfile, os, time
from collections import Counter
from PIL import Image
import yaml # Add this import for YAML parsing

# Eksik paket kontrolü
try:
    from sklearn.metrics import classification_report, confusion_matrix
    import matplotlib.pyplot as plt
    import seaborn as sns
    # yaml import'ını buraya da ekleyelim ki try bloğu başarılı olursa da erişilsin
    import yaml
except ImportError:
    os.system("pip install scikit-learn seaborn pyyaml -q") # Add pyyaml to installation
    from sklearn.metrics import classification_report, confusion_matrix
    import matplotlib.pyplot as plt
    import seaborn as sns
    import yaml

import warnings; warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────────────────────
# 1. CİHAZ & SEED
# ─────────────────────────────────────────────────────────────
device  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USE_AMP = device.type == 'cuda'   # Mixed precision sadece GPU'da
SEED    = 42
torch.manual_seed(SEED); np.random.seed(SEED)
if USE_AMP: torch.cuda.manual_seed_all(SEED)

print(f'{"="*60}')
print(f'  Cihaz  : {device}')
if USE_AMP:
    print(f'  GPU    : {torch.cuda.get_device_name(0)}')
    print(f'  Bellek : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')
else:
    print('  ⚠️  GPU yok! → Colab: Çalışma Zamanı > Donanım Hızlandırıcısını > T4 GPU')
print(f'{"="*60}\n')

# ─────────────────────────────────────────────────────────────
# 2. YAPILANDIRMA — sadece buradan değiştir
# ─────────────────────────────────────────────────────────────
CFG = dict(
    zip_path     = '/content/plantvillage.zip',      # Colab'a yüklediğin zip adı
    extract_dir  = './plantvillage_data', # Çıkarılacak dizin adı
    img_size     = 224,
    batch_size   = 32,          # T4 GPU için ideal; azalt → OOM hatası alırsan
    epochs       = 40,
    lr           = 3e-4,        # Classifier head için learning rate
    backbone_lr  = 3e-5,        # Pretrained backbone için (10× daha düşük olmalı)
    weight_decay = 5e-4,
    patience     = 8,           # Early stopping: kaç epoch iyileşme beklenecek
    warmup       = 5,           # İlk 5 epoch LR yavaşça artırılır
    val_split     = 0.20,        # Ayrı test klasörü yoksa val oranı
    # ── Model seçimi ──────────────────────────────────────────
    # 'efficientnet_b3' → daha hafif, hızlı, ~%70-78 acc beklenir
    # 'resnet50'        → biraz daha ağır, benzer accuracy
    model        = 'efficientnet_b3',
    save_path    = 'best_model.pth',
    workers      = 2           # DataLoader worker sayısı
)

# ─────────────────────────────────────────────────────────────
# 3. ZIP ÇIKARMA
# ─────────────────────────────────────────────────────────────
if not os.path.exists(CFG['extract_dir']):
    print(f'📦 {CFG["zip_path"]} çıkarılıyor...')
    try:
        with zipfile.ZipFile(CFG['zip_path'], 'r') as z:
            z.extractall(CFG['extract_dir'])
        print('✅ Çıkarma tamamlandı.\n')
    except FileNotFoundError:
        print(f'❌ "{CFG["zip_path"]}" bulunamadı! '
              'Colab sol menüsünden dosyalar sekmesine tam bu adla yükle.')
        raise
else:
    print('✅ Veri zaten çıkarılmış.\n')

# ─────────────────────────────────────────────────────────────
# 4. VERİ DİZİNLERİNİ OTOMATİK BUL & CUSTOM DATASET İÇİN HAZIRLA
# ─────────────────────────────────────────────────────────────
# The PlantVillage dataset has a structure like:
# ./plantvillage_data/plantvillage/PlantVillage/<class_name>/<image_files>
# So, the effective root for images is plantvillage_data/plantvillage/PlantVillage
data_root = Path(CFG['extract_dir']) / 'plantvillage' / 'PlantVillage'

if not data_root.is_dir():
    raise FileNotFoundError(f"Veri kök dizini bulunamadı: {data_root}. Lütfen ZIP dosyasının içeriğini kontrol edin.")

# Sınıf isimlerini dizin adlarından alalım
class_names = sorted([d.name for d in data_root.iterdir() if d.is_dir()])
num_classes = len(class_names)

if not class_names:
    raise RuntimeError("Veri kök dizininde hiçbir sınıf klasörü bulunamadı.")

class_to_idx = {name: i for i, name in enumerate(class_names)}
idx_to_class = {i: name for i, name in enumerate(class_names)}
classes = [idx_to_class[i] for i in sorted(idx_to_class.keys())] # Ensure 'classes' is sorted by index

# Remove data.yaml loading part as class names are already descriptive folder names.
print(f'✓ Veri kök dizini      : {data_root}')
print(f'✓ Sınıf sayısı         : {num_classes}')
print(f'✓ İlk 4 sınıf          : {classes[:4]}...')

# ─────────────────────────────────────────────────────────────
# Custom PlantDoc Dataset Sınıfı (Adapted for PlantVillage structure)
# ─────────────────────────────────────────────────────────────
class PlantDocDataset(Dataset):
    def __init__(self, root_dir, class_to_idx, transform=None):
        self.root_dir = Path(root_dir)
        self.class_to_idx = class_to_idx
        self.transform = transform
        self.samples = []

        # Her sınıf klasörünü gezerek resim ve etiket çiftlerini topla
        for class_name in sorted(os.listdir(self.root_dir)): # Iterate through class directories
            class_path = self.root_dir / class_name
            if not class_path.is_dir():
                continue

            class_idx = self.class_to_idx[class_name] # Get numerical index for class name

            for img_file in sorted(os.listdir(class_path)):
                if img_file.lower().endswith(('.png', '.jpg', '.jpeg')):
                    img_path = class_path / img_file
                    self.samples.append((img_path, class_idx))

        if not self.samples:
            raise FileNotFoundError(f"Belirtilen dizinde ({root_dir}) eşleşen resim ve etiket çifti bulunamadı. "
                                    "Sınıf klasörlerinin ve resimlerin doğru yerde olduğundan emin olun.")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)

        return image, label

# A wrapper to apply transformations to a Subset
class TransformedSubset(Dataset):
    def __init__(self, subset, transform=None):
        self.subset = subset
        self.transform = transform

    def __getitem__(self, idx):
        image, label = self.subset[idx]
        if self.transform:
            image = self.transform(image)
        return image, label

    def __len__(self):
        return len(self.subset)

# ─────────────────────────────────────────────────────────────
# 5. VERİ DÖNÜŞÜMÜ — Augmentation
# ─────────────────────────────────────────────────────────────
SZ   = CFG['img_size']
MEAN = [0.485, 0.456, 0.406]   # ImageNet istatistikleri (pretrained için önemli)
STD  = [0.229, 0.224, 0.225]

train_tf = transforms.Compose([
    transforms.Resize((SZ + 32, SZ + 32)),     # Biraz büyüt, sonra kırp
    transforms.RandomCrop(SZ),
    transforms.RandomHorizontalFlip(0.5),
    transforms.RandomVerticalFlip(0.2),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.3, contrast=0.3,
                           saturation=0.3, hue=0.1),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
    transforms.RandomErasing(p=0.15, scale=(0.02, 0.25)),  # Rastgele bölge sil
])

val_tf = transforms.Compose([
    transforms.Resize((SZ, SZ)),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

# ─────────────────────────────────────────────────────────────
# 6. DATASET & DATALOADER
# ─────────────────────────────────────────────────────────────
# Create a full dataset first, then split it into train/val/test
full_dataset = PlantDocDataset(root_dir=data_root, class_to_idx=class_to_idx)

n_total = len(full_dataset)

# Split into training+validation and test based on val_split ratio
# CFG['val_split'] is used as the test set ratio here for simplicity if no explicit test folder exists.
# Let's say val_split=0.2, then 20% for test, 80% for train+val.
test_size = int(n_total * CFG['val_split']) # Assign val_split ratio to test
train_val_size = n_total - test_size

generator = torch.Generator().manual_seed(SEED)

train_val_subset, test_subset_raw = random_split(full_dataset, [train_val_size, test_size], generator=generator)

# Now, split the train_val_subset into train and validation
# Using val_split again for the train_val_subset to get the validation set
val_size = int(len(train_val_subset) * CFG['val_split'])
train_size = len(train_val_subset) - val_size

train_subset_raw, val_subset_raw = random_split(train_val_subset, [train_size, val_size], generator=generator)

# Apply transforms using the TransformedSubset wrapper
train_ds = TransformedSubset(train_subset_raw, transform=train_tf)
val_ds = TransformedSubset(val_subset_raw, transform=val_tf)
test_ds = TransformedSubset(test_subset_raw, transform=val_tf)

# ── WeightedRandomSampler: sınıf dengesizliğini gider ───────

# Extract labels from the raw train_subset_raw (before transformation) to count classes
tr_labels = [sample[1] for sample in train_subset_raw]

cls_cnt   = Counter(tr_labels)
smp_w     = [1.0 / cls_cnt[l] for l in tr_labels]
sampler   = WeightedRandomSampler(
    weights=torch.tensor(smp_w, dtype=torch.float),
    num_samples=len(smp_w),
    replacement=True
)

pw = CFG['workers'] > 0   # persistent_workers sadece num_workers > 0'da geçerli
trainloader = DataLoader(train_ds, batch_size=CFG['batch_size'], sampler=sampler,
                         num_workers=CFG['workers'], pin_memory=True, persistent_workers=pw)
valloader   = DataLoader(val_ds,   batch_size=CFG['batch_size'], shuffle=False,
                         num_workers=CFG['workers'], pin_memory=True, persistent_workers=pw)
testloader  = DataLoader(test_ds,  batch_size=CFG['batch_size'], shuffle=False,
                         num_workers=CFG['workers'], pin_memory=True, persistent_workers=pw)

print(f'\n✓ Train: {len(train_ds):5d} | Val: {len(val_ds):5d} | Test: {len(test_ds):5d}')
print(f'✓ Batch: {len(trainloader)} train / {len(valloader)} val\n')

# ─────────────────────────────────────────────────────────────
# 7. MODEL OLUŞTURMA — Transfer Learning
# ─────────────────────────────────────────────────────────────
def build_model(name: str, nc: int) -> nn.Module:
    """
    ImageNet ile pretrained modeli yükle, son katmanı değiştir.
    Backbone'u dondurmuyoruz → fine-tuning (backbone_lr daha düşük tutulur).
    """
    if name == 'efficientnet_b3':
        m = models.efficientnet_b3(weights=models.EfficientNet_B3_Weights.IMAGENET1K_V1)
        in_f = m.classifier[1].in_features  # 1536
        m.classifier = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_f, 512),
            nn.SiLU(),
            nn.Dropout(0.2),
            nn.Linear(512, nc),
        )
    elif name == 'resnet50':
        m = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
        in_f = m.fc.in_features  # 2048
        m.fc = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_f, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.2),
            nn.Linear(512, nc),
        )
    else:
        raise ValueError(f"'{name}' geçersiz. 'efficientnet_b3' veya 'resnet50' girin.")
    return m

model = build_model(CFG['model'], num_classes).to(device)
print(f'✓ Model         : {CFG["model"]}')
print(f'  Toplam param  : {sum(p.numel() for p in model.parameters()):,}')
print(f'  Eğitilebilir  : {sum(p.numel() for p in model.parameters() if p.requires_grad):,}\n')

# ─────────────────────────────────────────────────────────────
# 8. LOSS / OPTIMIZER / SCHEDULER
# ─────────────────────────────────────────────────────────────
# Sınıf ağırlıklı kayıp + label smoothing (ezberlenmeyi azaltır)
w = torch.tensor(
    [1.0 / cls_cnt.get(i, 1) for i in range(num_classes)], dtype=torch.float
).to(device)
w = w / w.sum() * num_classes   # Normalize et
criterion = nn.CrossEntropyLoss(weight=w, label_smoothing=0.05)

# Backbone ve Head için farklı learning rate grupları
backbone_p, head_p = [], []
for pname, p in model.named_parameters():
    if any(k in pname for k in ('classifier', 'fc')):
        head_p.append(p)
    else:
        backbone_p.append(p)

optimizer = optim.AdamW(
    [{'params': backbone_p, 'lr': CFG['backbone_lr']},
     {'params': head_p,     'lr': CFG['lr']}],
    weight_decay=CFG['weight_decay']
)

# Warmup (5 epoch linear artış) + Cosine Annealing
from torch.optim.lr_scheduler import LinearLR, CosineAnnealingLR, SequentialLR
WU         = CFG['warmup']
sch_warm   = LinearLR(optimizer, start_factor=0.1, end_factor=1.0, total_iters=WU)
sch_cos    = CosineAnnealingLR(optimizer, T_max=max(CFG['epochs'] - WU, 1), eta_min=1e-7)
scheduler  = SequentialLR(optimizer, [sch_warm, sch_cos], milestones=[WU])

# Mixed Precision GradScaler (sadece GPU'da aktif)
scaler = torch.cuda.amp.GradScaler(enabled=USE_AMP)

# ─────────────────────────────────────────────────────────────
# 9. EĞİTİM / DOĞRULAMA YARDIMCI FONKSİYONU
# ─────────────────────────────────────────────────────────────
def run_epoch(model, loader, optimizer, criterion, scaler, train: bool):
    """
    Tek epoch eğitim (train=True) veya değerlendirme (train=False) yapar.
    Loss, accuracy, tahminler ve gerçek etiketleri döndürür.
    """
    model.train(train)
    total_loss = correct = total = 0
    all_pred, all_true = [], []

    with torch.set_grad_enabled(train):
        for imgs, lbls in loader:
            imgs = imgs.to(device, non_blocking=True)
            lbls = lbls.to(device, non_blocking=True)

            if train:
                optimizer.zero_grad(set_to_none=True)

            # Mixed precision forward pass
            with torch.cuda.amp.autocast(enabled=USE_AMP):
                out  = model(imgs)
                loss = criterion(out, lbls)

            if train:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)  # Patlayan gradientleri kes
                scaler.step(optimizer)
                scaler.update()

            pred = out.argmax(1)
            total_loss += loss.item() * imgs.size(0)
            correct    += (pred == lbls).sum().item()
            total      += imgs.size(0)
            all_pred.extend(pred.cpu().numpy())
            all_true.extend(lbls.cpu().numpy())

    return total_loss / total, correct / total, all_pred, all_true

# ─────────────────────────────────────────────────────────────
# 10. ANA EĞİTİM DÖNGÜSÜ
# ─────────────────────────────────────────────────────────────
hist = {k: [] for k in ('tl', 'ta', 'vl', 'va', 'lr')}
best_acc = best_ep = patience_cnt = 0

print(f'{"═"*70}')
print(f'  EĞİTİM  |  max {CFG["epochs"]} Epoch  |  {CFG["model"]}  |  {device}')
print(f'{"═"*70}')
print(f'{"Ep":>4}  {"TrLoss":>7}  {"TrAcc":>6}  {"VaLoss":>7}  {"VaAcc":>6}  {"LR":>9}  {"s":>5}')
print('─' * 70)

for ep in range(1, CFG['epochs'] + 1):
    t0 = time.time()

    tl, ta, _, _           = run_epoch(model, trainloader, optimizer, criterion, scaler, train=True)
    vl, va, val_pred, val_true = run_epoch(model, valloader, optimizer, criterion, scaler, train=False)
    scheduler.step()

    lr = optimizer.param_groups[1]['lr']   # Classifier head LR
    dt = time.time() - t0

    for k, v in zip(('tl','ta','vl','va','lr'), (tl, ta, vl, va, lr)):
        hist[k].append(v)

    flag = '  🏆' if va > best_acc else ''
    print(f'{ep:4d}  {tl:7.4f}  {ta*100:5.1f}%  {vl:7.4f}  {va*100:5.1f}%  {lr:9.2e}  {dt:5.1f}s{flag}')

    # En iyi modeli kaydet
    if va > best_acc:
        best_acc, best_ep, patience_cnt = va, ep, 0
        torch.save({
            'epoch'      : ep,
            'val_acc'    : va,
            'model_state': model.state_dict(),
            'optim_state': optimizer.state_dict(),
            'classes'    : classes, # Save the descriptive class names in the checkpoint
            'config'     : CFG
        }, CFG['save_path'])
    else:
        patience_cnt += 1
        if patience_cnt >= CFG['patience']:
            print(f'\n⏹  Early Stop — {CFG["patience"]} epoch boyunca iyileşme olmadı.')
            break

print(f'\n✅ Eğitim tamamlandı  |  Best Val: %{best_acc*100:.2f}  (Epoch {best_ep})')
print(f'   Kaydedildi → {CFG["save_path"]}\n')

# ─────────────────────────────────────────────────────────────
# 11. TEST DEĞERLENDİRMESİ (en iyi model ile)
# ─────────────────────────────────────────────────────────────
ckpt = torch.load(CFG['save_path'], map_location=device)
model.load_state_dict(ckpt['model_state'])
# `classes` variable is already updated with descriptive names from data.yaml, so use it.
# If not, you might need to reload it from ckpt['classes'] but it should be fine now.
print(f'📦 En iyi model yüklendi (Epoch {ckpt["epoch"]}, Val %{ckpt["val_acc"]*100:.2f})\n')

_, test_acc, tpred, ttrue = run_epoch(model, testloader, optimizer, criterion, scaler, train=False)
print(f'🎯 Test Accuracy : %{test_acc*100:.2f}\n')
print(classification_report(ttrue, tpred, target_names=classes, digits=3, zero_division=0)) # Use updated global 'classes'

# ─────────────────────────────────────────────────────────────
# 12. EĞİTİM GRAFİKLERİ
# ─────────────────────────────────────────────────────────────
eps_x = range(1, len(hist['tl']) + 1)
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle(f'PlantDoc | {CFG["model"]} | Best Val %{best_acc*100:.2f}',
             fontsize=14, fontweight='bold')

# Kayıp eğrisi
ax = axes[0]
ax.plot(eps_x, hist['tl'], label='Train', color='#E74C3C', lw=2)
ax.plot(eps_x, hist['vl'], label='Val',   color='#3498DB', lw=2)
ax.set(title='Loss Eğrisi', xlabel='Epoch', ylabel='Loss')
ax.legend(); ax.grid(alpha=0.3)

# Doğruluk eğrisi
ax = axes[1]
ax.plot(eps_x, [a*100 for a in hist['ta']], label='Train', color='#E74C3C', lw=2)
ax.plot(eps_x, [a*100 for a in hist['va']], label='Val',   color='#3498DB', lw=2)
ax.axhline(best_acc*100, color='#27AE60', ls='--', alpha=0.8,
           label=f'Best {best_acc*100:.1f}%')
ax.set(title='Doğruluk Eğrisi', xlabel='Epoch', ylabel='Accuracy (%)')
ax.legend(); ax.grid(alpha=0.3)

# Learning rate eğrisi
ax = axes[2]
ax.plot(eps_x, hist['lr'], color='#9B59B6', lw=2)
ax.set(title='Learning Rate Eğrisi', xlabel='Epoch', ylabel='LR')
ax.set_yscale('log'); ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('training_curves.png', dpi=150, bbox_inches='tight')
plt.show()

# Confusion Matrix
fig, ax = plt.subplots(figsize=(max(10, num_classes // 2), max(9, num_classes // 2)))
cm = confusion_matrix(ttrue, tpred)
sns.heatmap(cm, annot=(num_classes <= 30), fmt='d', cmap='Blues',
            xticklabels=classes, yticklabels=classes, ax=ax, annot_kws={'size': 7}) # Use updated global 'classes'
ax.set_title('Confusion Matrix', fontsize=13, fontweight='bold')
ax.set_ylabel('Gerçek Sınıf'); ax.set_xlabel('Tahmin Edilen')
plt.xticks(rotation=45, ha='right', fontsize=7)
plt.yticks(fontsize=7)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

print('📊 Grafikler kaydedildi: training_curves.png | confusion_matrix.png')

# ─────────────────────────────────────────────────────────────
# 13. TAHMİN FONKSİYONU
# ─────────────────────────────────────────────────────────────

def predict(img_path: str, top_k: int = 5):
    """
    Tek bir görseli sınıflandır ve top-k sonucu yazdır.

    Kullanım:
        predict('yaprak.jpg')           # top-5
        predict('yaprak.jpg', top_k=3) # top-3
    """
    # Tahmin fonksiyonunu daha sağlam hale getirmek için,
    # sınıf adlarını doğrudan checkpoint'ten yükleyelim.
    ckpt = torch.load(CFG['save_path'], map_location=device)
    model.load_state_dict(ckpt['model_state']) # Modelin doğru ağırlıklarla yüklendiğinden emin ol

    # ckpt['classes'] artık açıklayıcı isimleri içerdiğinden doğrudan kullanılabilir.
    current_classes = ckpt['classes'] # Sınıf adlarını checkpoint'ten al (şimdi açıklayıcı olmalı)

    tf = transforms.Compose([
        transforms.Resize((SZ, SZ)),
        transforms.ToTensor(),
        transforms.Normalize(MEAN, STD),
    ])
    img  = Image.open(img_path).convert('RGB')
    inp  = tf(img).unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        probs = torch.softmax(model(inp), dim=1)

    top_p, top_i = probs.topk(min(top_k, len(current_classes))) # 'num_classes' yerine 'len(current_classes)' kullan
    print(f'\n🌿  Tahmin: {img_path}')
    print('─' * 52)
    for p, i in zip(top_p[0], top_i[0]):
        bar = '█' * int(p.item() * 30)
        # 'current_classes' listesi artık açıklayıcı isimleri tuttuğu için doğrudan kullanılabilir.
        print(f'  {current_classes[i.item()]:38s} {bar} {p.item()*100:5.1f}%')

    best_class = current_classes[top_i[0][0].item()]
    best_prob  = top_p[0][0].item()
    print(f'\n  → Sonuç: {best_class}  (%{best_prob*100:.1f})')
    return best_class, best_prob


print('\n\n' + '═'*55)
print('✅  HER ŞEY TAMAMLANDI!')
print(f'   🏆  En İyi Val Acc  : %{best_acc*100:.2f}  (Epoch {best_ep})')
print(f'   💾  Model           : {CFG["save_path"]}')
print(f'   🌿  Tahmin yapmak   : predict("gorsel.jpg")')
print('═'*55)

readme_content = """
# Bitki Hastalığı Teşhisi: PlantDoc ve PlantVillage Veri Kümeleri

Bu proje, çeşitli bitki hastalıklarını tespit etmek için derin öğrenme modellerini kullanmaktadır. İki ana veri kümesi üzerinde çalışılmıştır: PlantDoc ve PlantVillage. Her iki veri kümesi için de ayrı ayrı model geliştirme ve değerlendirme süreçleri aşağıda özetlenmiştir.

## 1. PlantDoc Veri Kümesi (İlk Çalışma)

*(Kullanıcı isteği üzerine bu bölümdeki orijinal içerik korunmuştur. PlantDoc veri kümesiyle yapılan ilk çalışma burada yer alacaktır.)*

## 2. PlantVillage Veri Kümesi (Güncel Çalışma)

Bu bölümde, bitki hastalıklarını sınıflandırmak için yaygın olarak kullanılan PlantVillage veri kümesi üzerinde yapılan çalışmalar detaylandırılmıştır. Veri kümesi, farklı bitki türlerinin sağlıklı ve hastalıklı yaprak görsellerini içerir ve her sınıf, dizin yapıları aracılığıyla tanımlanmıştır.

### 2.1. Veri Hazırlığı ve Özelleştirme

PlantVillage veri kümesi, sınıf etiketlerini ayrı `.txt` dosyalarında tutmak yerine, resimlerin bulunduğu dizin adlarını kullanarak tanımlamaktadır. Bu yapıya uyum sağlamak için, mevcut veri yükleme betiği aşağıdaki şekillerde adapte edilmiştir:

*   **Veri Kök Dizini Ayarlaması**: Resimlerin gerçek kök dizini olan `./plantvillage_data/plantvillage/PlantVillage` yoluna işaret edecek şekilde `data_root` değişkeni güncellendi.
*   **Sınıf İsimlerinin Çıkarılması**: Sınıf isimleri, doğrudan bu kök dizin altındaki klasör adlarından otomatik olarak çıkarıldı.
*   **Özel `PlantDocDataset` Sınıfı**: `PlantDocDataset` sınıfı, dizin tabanlı sınıflandırma yapısına uygun olarak yeniden yazılarak, her bir sınıf klasöründeki görselleri ve bunlara karşılık gelen dizin adından türetilen sayısal etiketleri toplar hale getirildi.
*   **Veri Bölümleme**: Veri kümesi, eğitim, doğrulama ve test setlerine ayrılırken `random_split` ve `TransformedSubset` kullanılarak sağlam bir bölümleme sağlandı.

### 2.2. Model Eğitimi ve Sonuçları

Model, EfficientNet-B3 mimarisi kullanılarak eğitilmiştir. Eğitim süreci boyunca karışık hassasiyet (mixed precision) ve öğrenme oranı planlaması (learning rate scheduling) gibi teknikler kullanılmıştır. Erken durdurma (early stopping) mekanizması ile en iyi performans gösteren model kaydedilmiştir.

*   **En İyi Doğrulama Başarımı**: %99.61 (19. Epoch)
*   **Test Doğruluğu**: %99.52

#### Eğitim Eğrileri

Eğitim ve doğrulama kayıp ve doğruluk oranlarını ile öğrenme oranı değişimini gösteren grafikler aşağıdadır:

![Eğitim Eğrileri](training_curves.png)

#### Karmaşıklık Matrisi (Confusion Matrix)

Modelin test seti üzerindeki performansını detaylandıran karmaşıklık matrisi:

![Karmaşıklık Matrisi](confusion_matrix.png)

### 2.3. Görsel Tahmin Örneği

Eğitilen model, tekil görseller üzerinde tahmin yapmak için de kullanılabilmektedir. Aşağıda, `Pepper__bell___Bacterial_spot` sınıfına ait bir görsel için yapılan tahmin örneği ve sonuçları yer almaktadır:

```
🌿  Tahmin: /content/plantvillage_data/plantvillage/PlantVillage/Pepper__bell___Bacterial_spot/0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG
────────────────────────────────────────────────────
  Pepper__bell___Bacterial_spot          ████████████████████████████  95.0%
  Potato___healthy                          2.0%
  Tomato__Tomato_mosaic_virus               0.7%
  Tomato_Early_blight                       0.5%
  Potato___Late_blight                      0.3%

  → Sonuç: Pepper__bell___Bacterial_spot  (%95.0)
```

Bu çalışma, PlantVillage veri kümesiyle bitki hastalıklarının yüksek doğrulukla teşhis edilebileceğini göstermektedir. Elde edilen model, bitki hastalıklarının erken tespiti ve yönetimi konusunda önemli bir potansiyele sahiptir.
"""

with open('/content/README (1).md', 'w') as f:
    f.write(readme_content)

print("README (1).md dosyası başarıyla güncellendi.")

with open('/content/derinogrenme_odev_plantdoc.py', 'r') as f:
    script_content = f.read()
print(script_content)

!ls -R ./plantvillage_data

predict('/content/plantvillage_data/plantvillage/PlantVillage/Pepper__bell___Bacterial_spot/0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG')